In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

In [2]:
n = 6 # number of processess

In [3]:
# arrival time from 0.0 to 5.o 
arrival_times = np.random.randint(0, 50, size = n) / 10

# burst time from 0 to 25
burst_times = np.random.randint(1, 26, size = n)

# priorities unique from 1 to 6
priorities = np.random.choice(range(1, 7), size = n, replace=False)

process_ids = ["Process " + str(i+1) for i in range(n)]

response_time = np.zeros(6)

In [4]:
# Creating a dataframe
data = {
    "Process ID": process_ids,
    "Arrival Time": arrival_times,
    "Burst Time": burst_times,
    "Priority": priorities,
    "Status": ["new"] * len(process_ids),
    "Response Time": response_time,
    "Waiting Time": response_time,
    "Turnaround Time": response_time
}

quest = pd.DataFrame(data)

quest.head(6)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 1,4.0,12,2,new,0.0,0.0,0.0
1,Process 2,1.2,25,1,new,0.0,0.0,0.0
2,Process 3,1.1,15,6,new,0.0,0.0,0.0
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 6,1.3,24,5,new,0.0,0.0,0.0

In [5]:
# Final Report
def report(data):
    n = len(data)
    avg_resp = data['Response Time'].mean()
    avg_wait = data['Waiting Time'].mean()
    avg_turn = data['Turnaround Time'].mean()
    
    print(f"The average Response Time is: {avg_resp:.1f} unit time.")
    print(f"The average Waiting Time is: {avg_wait:.1f} unit time.")
    print(f"The average Turnaround Time is: {avg_turn:.1f} unit time.")

<h3>First Come First Serve Scheduling</h3>

In [6]:
def fcfs_scheduling(data):
    
    n = len(data)
    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    t = 0
    
    for i in range(0,n):
        if t < data1['Arrival Time'][i]:
            t = data1['Arrival Time'][i]
            
        data1.at[i,"Response Time"] = t - data1['Arrival Time'][i]
        data1.at[i,"Waiting Time"] = t - data1['Arrival Time'][i]
        t = t + data1['Burst Time'][i]
        data1.at[i,"Turnaround Time"] = t - data1['Arrival Time'][i]
        data1.at[i,"Status"] = "Completed"
        
        display(data1.head(6))
        
    return data1

In [7]:
data1 = fcfs_scheduling(quest)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,Completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,new,0.0,0.0,0.0
2,Process 6,1.3,24,5,new,0.0,0.0,0.0
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,Completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,Completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,new,0.0,0.0,0.0
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,Completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,Completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,Completed,39.8,39.8,63.8
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,Completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,Completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,Completed,39.8,39.8,63.8
3,Process 4,3.0,7,3,Completed,62.1,62.1,69.1
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,Completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,Completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,Completed,39.8,39.8,63.8
3,Process 4,3.0,7,3,Completed,62.1,62.1,69.1
4,Process 5,3.3,7,4,Completed,68.8,68.8,75.8
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,Completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,Completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,Completed,39.8,39.8,63.8
3,Process 4,3.0,7,3,Completed,62.1,62.1,69.1
4,Process 5,3.3,7,4,Completed,68.8,68.8,75.8
5,Process 1,4.0,12,2,Completed,75.1,75.1,87.1

In [8]:
report(data1)

The average Response Time is: 43.4 unit time.
The average Waiting Time is: 43.4 unit time.
The average Turnaround Time is: 58.4 unit time.

<h3>Shortest Job First Scheduling</h3>

In [9]:
def sjf_scheduling(data):
    
    n = len(data)
    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    t = 0
    completed_processes = 0
    process_queue = []
    current_time = data1['Arrival Time'][0]
    
    while completed_processes < n:
        
        # adding all processes that have arrived by the current time to the process queue
        for i in range(n):
            if data1.loc[i, 'Arrival Time'] <= current_time and data1.loc[i, 'Status'] == 'new':
                process_queue.append(i)
                data1.loc[i, 'Status'] = 'queued'
                       
        # Select the process with the shortest burst time from the process queue
        if process_queue:
            next_process = min(process_queue, key=lambda x: data1.loc[x, 'Burst Time'])
            process_queue.remove(next_process)
            
            if t < data1.loc[next_process, 'Arrival Time']:
                t = data1.loc[next_process, 'Arrival Time']
            
            data1.loc[next_process, 'Response Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Waiting Time'] = t - data1.loc[next_process, 'Arrival Time']
            t += data1.loc[next_process, 'Burst Time']
            data1.loc[next_process, 'Turnaround Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Status'] = 'completed'
            completed_processes += 1
            current_time += data1.loc[next_process, 'Turnaround Time']
            
        display(data1.head(6))

    return data1

In [10]:
data1 = sjf_scheduling(quest)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,new,0.0,0.0,0.0
2,Process 6,1.3,24,5,new,0.0,0.0,0.0
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,queued,0.0,0.0,0.0
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,completed,13.1,13.1,20.1
4,Process 5,3.3,7,4,queued,0.0,0.0,0.0
5,Process 1,4.0,12,2,queued,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,queued,0.0,0.0,0.0
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,completed,13.1,13.1,20.1
4,Process 5,3.3,7,4,completed,19.8,19.8,26.8
5,Process 1,4.0,12,2,queued,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,queued,0.0,0.0,0.0
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,completed,13.1,13.1,20.1
4,Process 5,3.3,7,4,completed,19.8,19.8,26.8
5,Process 1,4.0,12,2,completed,26.1,26.1,38.1

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,queued,0.0,0.0,0.0
2,Process 6,1.3,24,5,completed,40.8,40.8,64.8
3,Process 4,3.0,7,3,completed,13.1,13.1,20.1
4,Process 5,3.3,7,4,completed,19.8,19.8,26.8
5,Process 1,4.0,12,2,completed,26.1,26.1,38.1

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,completed,64.9,64.9,89.9
2,Process 6,1.3,24,5,completed,40.8,40.8,64.8
3,Process 4,3.0,7,3,completed,13.1,13.1,20.1
4,Process 5,3.3,7,4,completed,19.8,19.8,26.8
5,Process 1,4.0,12,2,completed,26.1,26.1,38.1

In [11]:
report(data1)

The average Response Time is: 27.4 unit time.
The average Waiting Time is: 27.4 unit time.
The average Turnaround Time is: 42.4 unit time.

<h3>Priority Scheduling</h3>

In [12]:
def prior_scheduling(data):
    
    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    n = len(data)
    t = 0
    completed_processes = 0
    process_queue = []
    current_time = data1['Arrival Time'][0]
    
    while completed_processes < n:
        
        # Adding all processes that have arrived by the current time to the process queue
        for i in range(n):
            if data1.loc[i, 'Arrival Time'] <= current_time and data1.loc[i, 'Status'] == 'new':
                process_queue.append(i)
                data1.loc[i, 'Status'] = 'queued'
        
        # Select the process with the most priority (1 being max) from the process queue
        if process_queue:
            next_process = min(process_queue, key=lambda x: data1.loc[x, 'Priority'])
            process_queue.remove(next_process)
            
            if t < data1.loc[next_process, 'Arrival Time']:
                t = data1.loc[next_process, 'Arrival Time']
            
            data1.loc[next_process, 'Response Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Waiting Time'] = t - data1.loc[next_process, 'Arrival Time']
            t += data1.loc[next_process, 'Burst Time']
            data1.loc[next_process, 'Turnaround Time'] = t - data1.loc[next_process, 'Arrival Time']
            data1.loc[next_process, 'Status'] = 'completed'
            completed_processes += 1
            
        else:
            current_time += data1.loc[next_process, 'Turnaround Time']
            
        display(data1.head(6))
        
    return data1

In [13]:
data1 = prior_scheduling(quest)

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,new,0.0,0.0,0.0
2,Process 6,1.3,24,5,new,0.0,0.0,0.0
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,new,0.0,0.0,0.0
2,Process 6,1.3,24,5,new,0.0,0.0,0.0
3,Process 4,3.0,7,3,new,0.0,0.0,0.0
4,Process 5,3.3,7,4,new,0.0,0.0,0.0
5,Process 1,4.0,12,2,new,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,queued,0.0,0.0,0.0
4,Process 5,3.3,7,4,queued,0.0,0.0,0.0
5,Process 1,4.0,12,2,queued,0.0,0.0,0.0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,queued,0.0,0.0,0.0
4,Process 5,3.3,7,4,queued,0.0,0.0,0.0
5,Process 1,4.0,12,2,completed,37.1,37.1,49.1

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,completed,50.1,50.1,57.1
4,Process 5,3.3,7,4,queued,0.0,0.0,0.0
5,Process 1,4.0,12,2,completed,37.1,37.1,49.1

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,queued,0.0,0.0,0.0
3,Process 4,3.0,7,3,completed,50.1,50.1,57.1
4,Process 5,3.3,7,4,completed,56.8,56.8,63.8
5,Process 1,4.0,12,2,completed,37.1,37.1,49.1

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time
0,Process 3,1.1,15,6,completed,0.0,0.0,15.0
1,Process 2,1.2,25,1,completed,14.9,14.9,39.9
2,Process 6,1.3,24,5,completed,65.8,65.8,89.8
3,Process 4,3.0,7,3,completed,50.1,50.1,57.1
4,Process 5,3.3,7,4,completed,56.8,56.8,63.8
5,Process 1,4.0,12,2,completed,37.1,37.1,49.1

In [14]:
report(data1)

The average Response Time is: 37.5 unit time.
The average Waiting Time is: 37.5 unit time.
The average Turnaround Time is: 52.4 unit time.

<h3>Round Robin Scheduling</h3>

In [15]:
def rr_scheduling(data):
    
    n = len(data)
    #quantum at 70 percentile
    quantum = 5 #int(np.percentile(data['Burst Time'], 70))

    print(f"The quantum is of size : {quantum}.")

    data1 = data.sort_values(by='Arrival Time').reset_index(drop=True)
    data1['Remaining Burst Time'] = data1['Burst Time']
        
    current_time = data1['Arrival Time'][0]
    
    while not all(data1['Status'] == 'Completed'):
        
        for i in range(n):
            
            if data1.loc[i, 'Status'] == 'new':
                data1.at[i, 'Response Time'] = current_time - data1.loc[i, 'Arrival Time']
                data1.at[i, 'Status'] = 'Processing'
                
                if data1.loc[i, 'Remaining Burst Time'] > quantum:
                    current_time += quantum
                    data1.at[i, 'Remaining Burst Time'] -= quantum
                    
                else:                    
                    current_time += data1.loc[i, 'Remaining Burst Time']
                    data1.at[i, 'Remaining Burst Time'] = 0
                    data1.at[i, 'Turnaround Time'] = current_time - data1.loc[i, 'Arrival Time']
                    data1.at[i, 'Waiting Time'] = data1.loc[i, 'Turnaround Time'] - data1.loc[i, 'Burst Time']
                    data1.at[i, 'Status'] = 'Completed' 
                    
                display(data1.head(6))
        
        for i in range(n):
            
            if data1.loc[i, 'Status'] == 'Processing':
                
                if data1.loc[i, 'Remaining Burst Time'] > quantum:
                    current_time += quantum
                    data1.at[i, 'Remaining Burst Time'] -= quantum
                    
                else:
                    current_time += data1.loc[i, 'Remaining Burst Time']
                    data1.at[i, 'Remaining Burst Time'] = 0
                    data1.at[i, 'Turnaround Time'] = current_time - data1.loc[i, 'Arrival Time']
                    data1.at[i, 'Waiting Time'] = data1.loc[i, 'Turnaround Time'] - data1.loc[i, 'Burst Time']
                    data1.at[i, 'Status'] = 'Completed'
                    
                display(data1.head(6))
    
    return data1

In [16]:
data1 = rr_scheduling(quest)

The quantum is of size : 5.

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,10
1,Process 2,1.2,25,1,new,0.0,0.0,0.0,25
2,Process 6,1.3,24,5,new,0.0,0.0,0.0,24
3,Process 4,3.0,7,3,new,0.0,0.0,0.0,7
4,Process 5,3.3,7,4,new,0.0,0.0,0.0,7
5,Process 1,4.0,12,2,new,0.0,0.0,0.0,12

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,10
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,20
2,Process 6,1.3,24,5,new,0.0,0.0,0.0,24
3,Process 4,3.0,7,3,new,0.0,0.0,0.0,7
4,Process 5,3.3,7,4,new,0.0,0.0,0.0,7
5,Process 1,4.0,12,2,new,0.0,0.0,0.0,12

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,10
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,20
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,19
3,Process 4,3.0,7,3,new,0.0,0.0,0.0,7
4,Process 5,3.3,7,4,new,0.0,0.0,0.0,7
5,Process 1,4.0,12,2,new,0.0,0.0,0.0,12

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,10
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,20
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,19
3,Process 4,3.0,7,3,Processing,13.1,0.0,0.0,2
4,Process 5,3.3,7,4,new,0.0,0.0,0.0,7
5,Process 1,4.0,12,2,new,0.0,0.0,0.0,12

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,10
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,20
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,19
3,Process 4,3.0,7,3,Processing,13.1,0.0,0.0,2
4,Process 5,3.3,7,4,Processing,17.8,0.0,0.0,2
5,Process 1,4.0,12,2,new,0.0,0.0,0.0,12

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,10
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,20
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,19
3,Process 4,3.0,7,3,Processing,13.1,0.0,0.0,2
4,Process 5,3.3,7,4,Processing,17.8,0.0,0.0,2
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,7

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,5
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,20
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,19
3,Process 4,3.0,7,3,Processing,13.1,0.0,0.0,2
4,Process 5,3.3,7,4,Processing,17.8,0.0,0.0,2
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,7

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,5
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,15
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,19
3,Process 4,3.0,7,3,Processing,13.1,0.0,0.0,2
4,Process 5,3.3,7,4,Processing,17.8,0.0,0.0,2
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,7

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,5
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,15
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,14
3,Process 4,3.0,7,3,Processing,13.1,0.0,0.0,2
4,Process 5,3.3,7,4,Processing,17.8,0.0,0.0,2
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,7

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,5
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,15
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,14
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Processing,17.8,0.0,0.0,2
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,7

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,5
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,15
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,14
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,7

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Processing,0.0,0.0,0.0,5
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,15
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,14
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,2

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,15
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,14
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,2

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,10
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,14
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,2

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,10
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,9
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Processing,22.1,0.0,0.0,2

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,10
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,9
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Completed,22.1,56.1,68.1,0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,5
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,9
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Completed,22.1,56.1,68.1,0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Processing,4.9,0.0,0.0,5
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,4
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Completed,22.1,56.1,68.1,0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Completed,4.9,60.9,85.9,0
2,Process 6,1.3,24,5,Processing,9.8,0.0,0.0,4
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Completed,22.1,56.1,68.1,0

,Process ID,Arrival Time,Burst Time,Priority,Status,Response Time,Waiting Time,Turnaround Time,Remaining Burst Time
0,Process 3,1.1,15,6,Completed,0.0,44.0,59.0,0
1,Process 2,1.2,25,1,Completed,4.9,60.9,85.9,0
2,Process 6,1.3,24,5,Completed,9.8,65.8,89.8,0
3,Process 4,3.0,7,3,Completed,13.1,38.1,45.1,0
4,Process 5,3.3,7,4,Completed,17.8,39.8,46.8,0
5,Process 1,4.0,12,2,Completed,22.1,56.1,68.1,0

In [17]:
report(data1)

The average Response Time is: 11.3 unit time.
The average Waiting Time is: 50.8 unit time.
The average Turnaround Time is: 65.8 unit time.